openapi: 3.1.0
info:
  title: Pockyt Online Payments API's
  version: 1.0.0
  description:
    $ref: introduction/_introduction.md

  license:
    name: Pockyt
    url: https://mapi.Pockyt.yunkeguan.com

  contact:
    name: API Team
    email: n@gwocu.com  
    url: https://gwocu.com/contact

tags:
  - name: API References
    description: Example Secure Pay operations. 
x-tagGroups:
  - name: API References
    tags:
      - API References
servers:
  - url: https://mapi.yuansfer.com
    description: Production
  - url: https://mapi.yuansfer.yunkeguan.com
    description: Sandbox

components:
  schemas: 
    secure-pay:
      $ref: ./schemas/secure-pay.yaml
    process:
      $ref: ./schemas/process.yaml
  securitySchemes:
    api_keys:
      description: |
        Generate your secret API key in the app settings.
      name: secret-key
      type: apiKey
      in: header
    jwt:
      description: |
        Generate your JWT when you log in.
      type: http
      scheme: bearer
      bearerFormat: JWT  
paths:
  /secure-pay:
    $ref: ./paths/secure-pay.yaml
  /process:
    $ref: ./paths/process.yaml